# Generated by Django 5.2.5 on 2025-08-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
    ]
